#!/bin/sh

# Создаём runtime config
cat > /app/build/env-config.js << EOF
window._env_ = {
  REACT_APP_API_ASSESSMENT_URL: "${REACT_APP_API_ASSESSMENT_URL}",
  REACT_APP_API_MEDIA_URL: "${REACT_APP_API_MEDIA_URL}",
  REACT_APP_API_IDENTIFY_URL: "${REACT_APP_API_IDENTIFY_URL}",
  REACT_APP_KEYCLOAK_URL: "${REACT_APP_KEYCLOAK_URL}",
  REACT_APP_KEYCLOAK_REALM: "${REACT_APP_KEYCLOAK_REALM}",
  REACT_APP_KEYCLOAK_CLIENT_ID: "${REACT_APP_KEYCLOAK_CLIENT_ID}",
  REACT_APP_KEYCLOAK_REDIRECT_PATH: "${REACT_APP_KEYCLOAK_REDIRECT_PATH}",
  REACT_APP_KEYCLOAK_SCOPE: "${REACT_APP_KEYCLOAK_SCOPE}",
  REACT_APP_KEYCLOAK_REFRESH_INTERVAL_MS: "${REACT_APP_KEYCLOAK_REFRESH_INTERVAL_MS}",
  REACT_APP_KEYCLOAK_REFRESH_LEEWAY_MS: "${REACT_APP_KEYCLOAK_REFRESH_LEEWAY_MS}"
};
EOF

# Запускаем приложение
exec "$@"
